[1] PRIORITY NUMBERS 
2016-11-28 13:34:09 [scrapy] ERROR: Spider error processing <GET https://worldwide.espacenet.com/data/publicationDetails/biblio?DB=EPODOC&II=23&ND=3&adjacent=true&locale=en_EP&FT=D&date=20161124&CC=WO&NR=2016187606A1&KC=A1> (referer: https://worldwide.espacenet.com/data/searchResults?page=399&locale=en_EP&DB=EPODOC&ST=advanced&TI=&AB=&PN=WO&AP=&PR=&PD=&PA=&IN=&CPC=&IC=&Submit=Search)
Traceback (most recent call last):
  File "c:\python27\lib\site-packages\scrapy\utils\defer.py", line 102, in iter_errback
    yield next(it)
  File "c:\python27\lib\site-packages\scrapy\spidermiddlewares\offsite.py", line 29, in process_spider_output
    for x in result:
  File "c:\python27\lib\site-packages\scrapy\spidermiddlewares\referer.py", line 22, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "c:\python27\lib\site-packages\scrapy\spidermiddlewares\urllength.py", line 37, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "c:\python27\lib\site-packages\scrapy\spidermiddlewares\depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "C:\Users\serap\Documents\inventtory_data_scraping\inventtory_data_scraping\inventtory_spiders\inventtory_spiders\spiders\ww_espacenet_WO.py", line 148, in parse_patent_link
    item['priority_numbers'] = response.xpath('//td[@class="printTableText"]//text()').re('(\w{2}\d{12}\s*\d{8})')[1]
IndexError: list index out of range
2016-11-28 13:34:15 [scrapy] ERROR: Spider error processing <GET https://worldwide.espacenet.com/data/publicationDetails/biblio?DB=EPODOC&II=22&ND=3&adjacent=true&locale=en_EP&FT=D&date=20161124&CC=WO&NR=2016187406A1&KC=A1> (referer: https://worldwide.espacenet.com/data/searchResults?page=399&locale=en_EP&DB=EPODOC&ST=advanced&TI=&AB=&PN=WO&AP=&PR=&PD=&PA=&IN=&CPC=&IC=&Submit=Search)
Traceback (most recent call last):
  File "c:\python27\lib\site-packages\scrapy\utils\defer.py", line 102, in iter_errback
    yield next(it)
  File "c:\python27\lib\site-packages\scrapy\spidermiddlewares\offsite.py", line 29, in process_spider_output
    for x in result:
  File "c:\python27\lib\site-packages\scrapy\spidermiddlewares\referer.py", line 22, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "c:\python27\lib\site-packages\scrapy\spidermiddlewares\urllength.py", line 37, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "c:\python27\lib\site-packages\scrapy\spidermiddlewares\depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "C:\Users\serap\Documents\inventtory_data_scraping\inventtory_data_scraping\inventtory_spiders\inventtory_spiders\spiders\ww_espacenet_WO.py", line 148, in parse_patent_link
    item['priority_numbers'] = response.xpath('//td[@class="printTableText"]//text()').re('(\w{2}\d{12}\s*\d{8})')[1]
IndexError: list index out of range
2016-11-28 13:34:29 [scrapy] ERROR: Spider error processing <GET https://worldwide.espacenet.com/data/publicationDetails/biblio?DB=EPODOC&II=20&ND=3&adjacent=true&locale=en_EP&FT=D&date=20161124&CC=WO&NR=2016186978A1&KC=A1> (referer: https://worldwide.espacenet.com/data/searchResults?page=399&locale=en_EP&DB=EPODOC&ST=advanced&TI=&AB=&PN=WO&AP=&PR=&PD=&PA=&IN=&CPC=&IC=&Submit=Search)
Traceback (most recent call last):
  File "c:\python27\lib\site-packages\scrapy\utils\defer.py", line 102, in iter_errback
    yield next(it)
  File "c:\python27\lib\site-packages\scrapy\spidermiddlewares\offsite.py", line 29, in process_spider_output
    for x in result:
  File "c:\python27\lib\site-packages\scrapy\spidermiddlewares\referer.py", line 22, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "c:\python27\lib\site-packages\scrapy\spidermiddlewares\urllength.py", line 37, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "c:\python27\lib\site-packages\scrapy\spidermiddlewares\depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "C:\Users\serap\Documents\inventtory_data_scraping\inventtory_data_scraping\inventtory_spiders\inventtory_spiders\spiders\ww_espacenet_WO.py", line 148, in parse_patent_link
    item['priority_numbers'] = response.xpath('//td[@class="printTableText"]//text()').re('(\w{2}\d{12}\s*\d{8})')[1]
IndexError: list index out of range
2016-11-28 13:34:37 [scrapy] ERROR: Spider error processing <GET https://worldwide.espacenet.com/data/publicationDetails/biblio?DB=EPODOC&II=19&ND=3&adjacent=true&locale=en_EP&FT=D&date=20161124&CC=WO&NR=2016186907A1&KC=A1> (referer: https://worldwide.espacenet.com/data/searchResults?page=399&locale=en_EP&DB=EPODOC&ST=advanced&TI=&AB=&PN=WO&AP=&PR=&PD=&PA=&IN=&CPC=&IC=&Submit=Search)
Traceback (most recent call last):
  File "c:\python27\lib\site-packages\scrapy\utils\defer.py", line 102, in iter_errback
    yield next(it)
  File "c:\python27\lib\site-packages\scrapy\spidermiddlewares\offsite.py", line 29, in process_spider_output
    for x in result:
  File "c:\python27\lib\site-packages\scrapy\spidermiddlewares\referer.py", line 22, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "c:\python27\lib\site-packages\scrapy\spidermiddlewares\urllength.py", line 37, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "c:\python27\lib\site-packages\scrapy\spidermiddlewares\depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "C:\Users\serap\Documents\inventtory_data_scraping\inventtory_data_scraping\inventtory_spiders\inventtory_spiders\spiders\ww_espacenet_WO.py", line 148, in parse_patent_link
    item['priority_numbers'] = response.xpath('//td[@class="printTableText"]//text()').re('(\w{2}\d{12}\s*\d{8})')[1]
IndexError: list index out of range
2016-11-28 13:34:42 [scrapy] ERROR: Spider error processing <GET https://worldwide.espacenet.com/data/publicationDetails/biblio?DB=EPODOC&II=18&ND=3&adjacent=true&locale=en_EP&FT=D&date=20161124&CC=WO&NR=2016186797A1&KC=A1> (referer: https://worldwide.espacenet.com/data/searchResults?page=399&locale=en_EP&DB=EPODOC&ST=advanced&TI=&AB=&PN=WO&AP=&PR=&PD=&PA=&IN=&CPC=&IC=&Submit=Search)
Traceback (most recent call last):
  File "c:\python27\lib\site-packages\scrapy\utils\defer.py", line 102, in iter_errback
    yield next(it)
  File "c:\python27\lib\site-packages\scrapy\spidermiddlewares\offsite.py", line 29, in process_spider_output
    for x in result:
  File "c:\python27\lib\site-packages\scrapy\spidermiddlewares\referer.py", line 22, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "c:\python27\lib\site-packages\scrapy\spidermiddlewares\urllength.py", line 37, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "c:\python27\lib\site-packages\scrapy\spidermiddlewares\depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "C:\Users\serap\Documents\inventtory_data_scraping\inventtory_data_scraping\inventtory_spiders\inventtory_spiders\spiders\ww_espacenet_WO.py", line 148, in parse_patent_link
    item['priority_numbers'] = response.xpath('//td[@class="printTableText"]//text()').re('(\w{2}\d{12}\s*\d{8})')[1]
IndexError: list index out of range
2016-11-28 13:34:49 [scrapy] ERROR: Spider error processing <GET https://worldwide.espacenet.com/data/publicationDetails/biblio?DB=EPODOC&II=17&ND=3&adjacent=true&locale=en_EP&FT=D&date=20161124&CC=WO&NR=2016186737A1&KC=A1> (referer: https://worldwide.espacenet.com/data/searchResults?page=399&locale=en_EP&DB=EPODOC&ST=advanced&TI=&AB=&PN=WO&AP=&PR=&PD=&PA=&IN=&CPC=&IC=&Submit=Search)
Traceback (most recent call last):
  File "c:\python27\lib\site-packages\scrapy\utils\defer.py", line 102, in iter_errback
    yield next(it)
  File "c:\python27\lib\site-packages\scrapy\spidermiddlewares\offsite.py", line 29, in process_spider_output
    for x in result:
  File "c:\python27\lib\site-packages\scrapy\spidermiddlewares\referer.py", line 22, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "c:\python27\lib\site-packages\scrapy\spidermiddlewares\urllength.py", line 37, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "c:\python27\lib\site-packages\scrapy\spidermiddlewares\depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "C:\Users\serap\Documents\inventtory_data_scraping\inventtory_data_scraping\inventtory_spiders\inventtory_spiders\spiders\ww_espacenet_WO.py", line 148, in parse_patent_link
    item['priority_numbers'] = response.xpath('//td[@class="printTableText"]//text()').re('(\w{2}\d{12}\s*\d{8})')[1]
IndexError: list index out of range
2016-11-28 13:34:55 [scrapy] ERROR: Spider error processing <GET https://worldwide.espacenet.com/data/publicationDetails/biblio?DB=EPODOC&II=16&ND=3&adjacent=true&locale=en_EP&FT=D&date=20161124&CC=WO&NR=2016186693A1&KC=A1> (referer: https://worldwide.espacenet.com/data/searchResults?page=399&locale=en_EP&DB=EPODOC&ST=advanced&TI=&AB=&PN=WO&AP=&PR=&PD=&PA=&IN=&CPC=&IC=&Submit=Search)
Traceback (most recent call last):
  File "c:\python27\lib\site-packages\scrapy\utils\defer.py", line 102, in iter_errback
    yield next(it)
  File "c:\python27\lib\site-packages\scrapy\spidermiddlewares\offsite.py", line 29, in process_spider_output
    for x in result:
  File "c:\python27\lib\site-packages\scrapy\spidermiddlewares\referer.py", line 22, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "c:\python27\lib\site-packages\scrapy\spidermiddlewares\urllength.py", line 37, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "c:\python27\lib\site-packages\scrapy\spidermiddlewares\depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "C:\Users\serap\Documents\inventtory_data_scraping\inventtory_data_scraping\inventtory_spiders\inventtory_spiders\spiders\ww_espacenet_WO.py", line 148, in parse_patent_link
    item['priority_numbers'] = response.xpath('//td[@class="printTableText"]//text()').re('(\w{2}\d{12}\s*\d{8})')[1]
IndexError: list index out of range
2016-11-28 13:46:06 [scrapy] ERROR: Spider error processing <GET https://worldwide.espacenet.com/data/publicationDetails/biblio?DB=EPODOC&II=23&ND=3&adjacent=true&locale=en_EP&FT=D&date=20161124&CC=WO&NR=2016187606A1&KC=A1> (referer: https://worldwide.espacenet.com/data/searchResults?page=70&locale=en_EP&DB=EPODOC&ST=advanced&TI=&AB=&PN=WO&AP=&PR=&PD=&PA=&IN=&CPC=&IC=&Submit=Search)
Traceback (most recent call last):
  File "c:\python27\lib\site-packages\scrapy\utils\defer.py", line 102, in iter_errback
    yield next(it)
  File "c:\python27\lib\site-packages\scrapy\spidermiddlewares\offsite.py", line 29, in process_spider_output
    for x in result:
  File "c:\python27\lib\site-packages\scrapy\spidermiddlewares\referer.py", line 22, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "c:\python27\lib\site-packages\scrapy\spidermiddlewares\urllength.py", line 37, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "c:\python27\lib\site-packages\scrapy\spidermiddlewares\depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "C:\Users\serap\Documents\inventtory_data_scraping\inventtory_data_scraping\inventtory_spiders\inventtory_spiders\spiders\ww_espacenet_WO.py", line 148, in parse_patent_link
    item['priority_numbers'] = response.xpath('//td[@class="printTableText"]//text()').re('(\w{2}\d{12}\s*\d{8})')[1]
IndexError: list index out of range
2016-11-28 13:46:39 [scrapy] ERROR: Spider error processing <GET https://worldwide.espacenet.com/data/publicationDetails/biblio?DB=EPODOC&II=22&ND=3&adjacent=true&locale=en_EP&FT=D&date=20161124&CC=WO&NR=2016187406A1&KC=A1> (referer: https://worldwide.espacenet.com/data/searchResults?page=70&locale=en_EP&DB=EPODOC&ST=advanced&TI=&AB=&PN=WO&AP=&PR=&PD=&PA=&IN=&CPC=&IC=&Submit=Search)
Traceback (most recent call last):
  File "c:\python27\lib\site-packages\scrapy\utils\defer.py", line 102, in iter_errback
    yield next(it)
  File "c:\python27\lib\site-packages\scrapy\spidermiddlewares\offsite.py", line 29, in process_spider_output
    for x in result:
  File "c:\python27\lib\site-packages\scrapy\spidermiddlewares\referer.py", line 22, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "c:\python27\lib\site-packages\scrapy\spidermiddlewares\urllength.py", line 37, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "c:\python27\lib\site-packages\scrapy\spidermiddlewares\depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "C:\Users\serap\Documents\inventtory_data_scraping\inventtory_data_scraping\inventtory_spiders\inventtory_spiders\spiders\ww_espacenet_WO.py", line 148, in parse_patent_link
    item['priority_numbers'] = response.xpath('//td[@class="printTableText"]//text()').re('(\w{2}\d{12}\s*\d{8})')[1]
IndexError: list index out of range
2016-11-28 13:46:52 [scrapy] ERROR: Spider error processing <GET https://worldwide.espacenet.com/data/publicationDetails/biblio?DB=EPODOC&II=20&ND=3&adjacent=true&locale=en_EP&FT=D&date=20161124&CC=WO&NR=2016186978A1&KC=A1> (referer: https://worldwide.espacenet.com/data/searchResults?page=70&locale=en_EP&DB=EPODOC&ST=advanced&TI=&AB=&PN=WO&AP=&PR=&PD=&PA=&IN=&CPC=&IC=&Submit=Search)
Traceback (most recent call last):
  File "c:\python27\lib\site-packages\scrapy\utils\defer.py", line 102, in iter_errback
    yield next(it)
  File "c:\python27\lib\site-packages\scrapy\spidermiddlewares\offsite.py", line 29, in process_spider_output
    for x in result:
  File "c:\python27\lib\site-packages\scrapy\spidermiddlewares\referer.py", line 22, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "c:\python27\lib\site-packages\scrapy\spidermiddlewares\urllength.py", line 37, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "c:\python27\lib\site-packages\scrapy\spidermiddlewares\depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "C:\Users\serap\Documents\inventtory_data_scraping\inventtory_data_scraping\inventtory_spiders\inventtory_spiders\spiders\ww_espacenet_WO.py", line 148, in parse_patent_link
    item['priority_numbers'] = response.xpath('//td[@class="printTableText"]//text()').re('(\w{2}\d{12}\s*\d{8})')[1]
IndexError: list index out of range
2016-11-28 13:46:58 [scrapy] ERROR: Spider error processing <GET https://worldwide.espacenet.com/data/publicationDetails/biblio?DB=EPODOC&II=19&ND=3&adjacent=true&locale=en_EP&FT=D&date=20161124&CC=WO&NR=2016186907A1&KC=A1> (referer: https://worldwide.espacenet.com/data/searchResults?page=70&locale=en_EP&DB=EPODOC&ST=advanced&TI=&AB=&PN=WO&AP=&PR=&PD=&PA=&IN=&CPC=&IC=&Submit=Search)
Traceback (most recent call last):
  File "c:\python27\lib\site-packages\scrapy\utils\defer.py", line 102, in iter_errback
    yield next(it)
  File "c:\python27\lib\site-packages\scrapy\spidermiddlewares\offsite.py", line 29, in process_spider_output
    for x in result:
  File "c:\python27\lib\site-packages\scrapy\spidermiddlewares\referer.py", line 22, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "c:\python27\lib\site-packages\scrapy\spidermiddlewares\urllength.py", line 37, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "c:\python27\lib\site-packages\scrapy\spidermiddlewares\depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "C:\Users\serap\Documents\inventtory_data_scraping\inventtory_data_scraping\inventtory_spiders\inventtory_spiders\spiders\ww_espacenet_WO.py", line 148, in parse_patent_link
    item['priority_numbers'] = response.xpath('//td[@class="printTableText"]//text()').re('(\w{2}\d{12}\s*\d{8})')[1]
IndexError: list index out of range
2016-11-28 13:47:05 [scrapy] ERROR: Spider error processing <GET https://worldwide.espacenet.com/data/publicationDetails/biblio?DB=EPODOC&II=18&ND=3&adjacent=true&locale=en_EP&FT=D&date=20161124&CC=WO&NR=2016186797A1&KC=A1> (referer: https://worldwide.espacenet.com/data/searchResults?page=70&locale=en_EP&DB=EPODOC&ST=advanced&TI=&AB=&PN=WO&AP=&PR=&PD=&PA=&IN=&CPC=&IC=&Submit=Search)
Traceback (most recent call last):
  File "c:\python27\lib\site-packages\scrapy\utils\defer.py", line 102, in iter_errback
    yield next(it)
  File "c:\python27\lib\site-packages\scrapy\spidermiddlewares\offsite.py", line 29, in process_spider_output
    for x in result:
  File "c:\python27\lib\site-packages\scrapy\spidermiddlewares\referer.py", line 22, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "c:\python27\lib\site-packages\scrapy\spidermiddlewares\urllength.py", line 37, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "c:\python27\lib\site-packages\scrapy\spidermiddlewares\depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "C:\Users\serap\Documents\inventtory_data_scraping\inventtory_data_scraping\inventtory_spiders\inventtory_spiders\spiders\ww_espacenet_WO.py", line 148, in parse_patent_link
    item['priority_numbers'] = response.xpath('//td[@class="printTableText"]//text()').re('(\w{2}\d{12}\s*\d{8})')[1]
IndexError: list index out of range
2016-11-28 13:47:12 [scrapy] ERROR: Spider error processing <GET https://worldwide.espacenet.com/data/publicationDetails/biblio?DB=EPODOC&II=17&ND=3&adjacent=true&locale=en_EP&FT=D&date=20161124&CC=WO&NR=2016186737A1&KC=A1> (referer: https://worldwide.espacenet.com/data/searchResults?page=70&locale=en_EP&DB=EPODOC&ST=advanced&TI=&AB=&PN=WO&AP=&PR=&PD=&PA=&IN=&CPC=&IC=&Submit=Search)
Traceback (most recent call last):
  File "c:\python27\lib\site-packages\scrapy\utils\defer.py", line 102, in iter_errback
    yield next(it)
  File "c:\python27\lib\site-packages\scrapy\spidermiddlewares\offsite.py", line 29, in process_spider_output
    for x in result:
  File "c:\python27\lib\site-packages\scrapy\spidermiddlewares\referer.py", line 22, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "c:\python27\lib\site-packages\scrapy\spidermiddlewares\urllength.py", line 37, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "c:\python27\lib\site-packages\scrapy\spidermiddlewares\depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "C:\Users\serap\Documents\inventtory_data_scraping\inventtory_data_scraping\inventtory_spiders\inventtory_spiders\spiders\ww_espacenet_WO.py", line 148, in parse_patent_link
    item['priority_numbers'] = response.xpath('//td[@class="printTableText"]//text()').re('(\w{2}\d{12}\s*\d{8})')[1]
IndexError: list index out of range
2016-11-28 13:47:19 [scrapy] ERROR: Spider error processing <GET https://worldwide.espacenet.com/data/publicationDetails/biblio?DB=EPODOC&II=16&ND=3&adjacent=true&locale=en_EP&FT=D&date=20161124&CC=WO&NR=2016186693A1&KC=A1> (referer: https://worldwide.espacenet.com/data/searchResults?page=70&locale=en_EP&DB=EPODOC&ST=advanced&TI=&AB=&PN=WO&AP=&PR=&PD=&PA=&IN=&CPC=&IC=&Submit=Search)
Traceback (most recent call last):
  File "c:\python27\lib\site-packages\scrapy\utils\defer.py", line 102, in iter_errback
    yield next(it)
  File "c:\python27\lib\site-packages\scrapy\spidermiddlewares\offsite.py", line 29, in process_spider_output
    for x in result:
  File "c:\python27\lib\site-packages\scrapy\spidermiddlewares\referer.py", line 22, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "c:\python27\lib\site-packages\scrapy\spidermiddlewares\urllength.py", line 37, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "c:\python27\lib\site-packages\scrapy\spidermiddlewares\depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "C:\Users\serap\Documents\inventtory_data_scraping\inventtory_data_scraping\inventtory_spiders\inventtory_spiders\spiders\ww_espacenet_WO.py", line 148, in parse_patent_link
    item['priority_numbers'] = response.xpath('//td[@class="printTableText"]//text()').re('(\w{2}\d{12}\s*\d{8})')[1]
IndexError: list index out of range
2016-11-28 13:49:06 [scrapy] ERROR: Spider error processing <GET https://worldwide.espacenet.com/data/publicationDetails/biblio?DB=EPODOC&II=23&ND=3&adjacent=true&locale=en_EP&FT=D&date=20161124&CC=WO&NR=2016187606A1&KC=A1> (referer: https://worldwide.espacenet.com/data/searchResults?page=71&locale=en_EP&DB=EPODOC&ST=advanced&TI=&AB=&PN=WO&AP=&PR=&PD=&PA=&IN=&CPC=&IC=&Submit=Search)
Traceback (most recent call last):
  File "c:\python27\lib\site-packages\scrapy\utils\defer.py", line 102, in iter_errback
    yield next(it)
  File "c:\python27\lib\site-packages\scrapy\spidermiddlewares\offsite.py", line 29, in process_spider_output
    for x in result:
  File "c:\python27\lib\site-packages\scrapy\spidermiddlewares\referer.py", line 22, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "c:\python27\lib\site-packages\scrapy\spidermiddlewares\urllength.py", line 37, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "c:\python27\lib\site-packages\scrapy\spidermiddlewares\depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "C:\Users\serap\Documents\inventtory_data_scraping\inventtory_data_scraping\inventtory_spiders\inventtory_spiders\spiders\ww_espacenet_WO.py", line 148, in parse_patent_link
    item['priority_numbers'] = response.xpath('//td[@class="printTableText"]//text()').re('(\w{2}\d{12}\s*\d{8})')[1]
IndexError: list index out of range
2016-11-28 13:49:18 [scrapy] ERROR: Spider error processing <GET https://worldwide.espacenet.com/data/publicationDetails/biblio?DB=EPODOC&II=22&ND=3&adjacent=true&locale=en_EP&FT=D&date=20161124&CC=WO&NR=2016187406A1&KC=A1> (referer: https://worldwide.espacenet.com/data/searchResults?page=71&locale=en_EP&DB=EPODOC&ST=advanced&TI=&AB=&PN=WO&AP=&PR=&PD=&PA=&IN=&CPC=&IC=&Submit=Search)
Traceback (most recent call last):
  File "c:\python27\lib\site-packages\scrapy\utils\defer.py", line 102, in iter_errback
    yield next(it)
  File "c:\python27\lib\site-packages\scrapy\spidermiddlewares\offsite.py", line 29, in process_spider_output
    for x in result:
  File "c:\python27\lib\site-packages\scrapy\spidermiddlewares\referer.py", line 22, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "c:\python27\lib\site-packages\scrapy\spidermiddlewares\urllength.py", line 37, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "c:\python27\lib\site-packages\scrapy\spidermiddlewares\depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "C:\Users\serap\Documents\inventtory_data_scraping\inventtory_data_scraping\inventtory_spiders\inventtory_spiders\spiders\ww_espacenet_WO.py", line 148, in parse_patent_link
    item['priority_numbers'] = response.xpath('//td[@class="printTableText"]//text()').re('(\w{2}\d{12}\s*\d{8})')[1]
IndexError: list index out of range
2016-11-28 13:49:33 [scrapy] ERROR: Spider error processing <GET https://worldwide.espacenet.com/data/publicationDetails/biblio?DB=EPODOC&II=20&ND=3&adjacent=true&locale=en_EP&FT=D&date=20161124&CC=WO&NR=2016186978A1&KC=A1> (referer: https://worldwide.espacenet.com/data/searchResults?page=71&locale=en_EP&DB=EPODOC&ST=advanced&TI=&AB=&PN=WO&AP=&PR=&PD=&PA=&IN=&CPC=&IC=&Submit=Search)
Traceback (most recent call last):
  File "c:\python27\lib\site-packages\scrapy\utils\defer.py", line 102, in iter_errback
    yield next(it)
  File "c:\python27\lib\site-packages\scrapy\spidermiddlewares\offsite.py", line 29, in process_spider_output
    for x in result:
  File "c:\python27\lib\site-packages\scrapy\spidermiddlewares\referer.py", line 22, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "c:\python27\lib\site-packages\scrapy\spidermiddlewares\urllength.py", line 37, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "c:\python27\lib\site-packages\scrapy\spidermiddlewares\depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "C:\Users\serap\Documents\inventtory_data_scraping\inventtory_data_scraping\inventtory_spiders\inventtory_spiders\spiders\ww_espacenet_WO.py", line 148, in parse_patent_link
    item['priority_numbers'] = response.xpath('//td[@class="printTableText"]//text()').re('(\w{2}\d{12}\s*\d{8})')[1]
IndexError: list index out of range
2016-11-28 13:49:40 [scrapy] ERROR: Spider error processing <GET https://worldwide.espacenet.com/data/publicationDetails/biblio?DB=EPODOC&II=19&ND=3&adjacent=true&locale=en_EP&FT=D&date=20161124&CC=WO&NR=2016186907A1&KC=A1> (referer: https://worldwide.espacenet.com/data/searchResults?page=71&locale=en_EP&DB=EPODOC&ST=advanced&TI=&AB=&PN=WO&AP=&PR=&PD=&PA=&IN=&CPC=&IC=&Submit=Search)
Traceback (most recent call last):
  File "c:\python27\lib\site-packages\scrapy\utils\defer.py", line 102, in iter_errback
    yield next(it)
  File "c:\python27\lib\site-packages\scrapy\spidermiddlewares\offsite.py", line 29, in process_spider_output
    for x in result:
  File "c:\python27\lib\site-packages\scrapy\spidermiddlewares\referer.py", line 22, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "c:\python27\lib\site-packages\scrapy\spidermiddlewares\urllength.py", line 37, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "c:\python27\lib\site-packages\scrapy\spidermiddlewares\depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "C:\Users\serap\Documents\inventtory_data_scraping\inventtory_data_scraping\inventtory_spiders\inventtory_spiders\spiders\ww_espacenet_WO.py", line 148, in parse_patent_link
    item['priority_numbers'] = response.xpath('//td[@class="printTableText"]//text()').re('(\w{2}\d{12}\s*\d{8})')[1]
IndexError: list index out of range
2016-11-28 13:49:46 [scrapy] ERROR: Spider error processing <GET https://worldwide.espacenet.com/data/publicationDetails/biblio?DB=EPODOC&II=18&ND=3&adjacent=true&locale=en_EP&FT=D&date=20161124&CC=WO&NR=2016186797A1&KC=A1> (referer: https://worldwide.espacenet.com/data/searchResults?page=71&locale=en_EP&DB=EPODOC&ST=advanced&TI=&AB=&PN=WO&AP=&PR=&PD=&PA=&IN=&CPC=&IC=&Submit=Search)
Traceback (most recent call last):
  File "c:\python27\lib\site-packages\scrapy\utils\defer.py", line 102, in iter_errback
    yield next(it)
  File "c:\python27\lib\site-packages\scrapy\spidermiddlewares\offsite.py", line 29, in process_spider_output
    for x in result:
  File "c:\python27\lib\site-packages\scrapy\spidermiddlewares\referer.py", line 22, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "c:\python27\lib\site-packages\scrapy\spidermiddlewares\urllength.py", line 37, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "c:\python27\lib\site-packages\scrapy\spidermiddlewares\depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "C:\Users\serap\Documents\inventtory_data_scraping\inventtory_data_scraping\inventtory_spiders\inventtory_spiders\spiders\ww_espacenet_WO.py", line 148, in parse_patent_link
    item['priority_numbers'] = response.xpath('//td[@class="printTableText"]//text()').re('(\w{2}\d{12}\s*\d{8})')[1]
IndexError: list index out of range
2016-11-28 13:49:53 [scrapy] ERROR: Spider error processing <GET https://worldwide.espacenet.com/data/publicationDetails/biblio?DB=EPODOC&II=17&ND=3&adjacent=true&locale=en_EP&FT=D&date=20161124&CC=WO&NR=2016186737A1&KC=A1> (referer: https://worldwide.espacenet.com/data/searchResults?page=71&locale=en_EP&DB=EPODOC&ST=advanced&TI=&AB=&PN=WO&AP=&PR=&PD=&PA=&IN=&CPC=&IC=&Submit=Search)
Traceback (most recent call last):
  File "c:\python27\lib\site-packages\scrapy\utils\defer.py", line 102, in iter_errback
    yield next(it)
  File "c:\python27\lib\site-packages\scrapy\spidermiddlewares\offsite.py", line 29, in process_spider_output
    for x in result:
  File "c:\python27\lib\site-packages\scrapy\spidermiddlewares\referer.py", line 22, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "c:\python27\lib\site-packages\scrapy\spidermiddlewares\urllength.py", line 37, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "c:\python27\lib\site-packages\scrapy\spidermiddlewares\depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "C:\Users\serap\Documents\inventtory_data_scraping\inventtory_data_scraping\inventtory_spiders\inventtory_spiders\spiders\ww_espacenet_WO.py", line 148, in parse_patent_link
    item['priority_numbers'] = response.xpath('//td[@class="printTableText"]//text()').re('(\w{2}\d{12}\s*\d{8})')[1]
IndexError: list index out of range
2016-11-28 13:49:58 [scrapy] ERROR: Spider error processing <GET https://worldwide.espacenet.com/data/publicationDetails/biblio?DB=EPODOC&II=16&ND=3&adjacent=true&locale=en_EP&FT=D&date=20161124&CC=WO&NR=2016186693A1&KC=A1> (referer: https://worldwide.espacenet.com/data/searchResults?page=71&locale=en_EP&DB=EPODOC&ST=advanced&TI=&AB=&PN=WO&AP=&PR=&PD=&PA=&IN=&CPC=&IC=&Submit=Search)
Traceback (most recent call last):
  File "c:\python27\lib\site-packages\scrapy\utils\defer.py", line 102, in iter_errback
    yield next(it)
  File "c:\python27\lib\site-packages\scrapy\spidermiddlewares\offsite.py", line 29, in process_spider_output
    for x in result:
  File "c:\python27\lib\site-packages\scrapy\spidermiddlewares\referer.py", line 22, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "c:\python27\lib\site-packages\scrapy\spidermiddlewares\urllength.py", line 37, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "c:\python27\lib\site-packages\scrapy\spidermiddlewares\depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "C:\Users\serap\Documents\inventtory_data_scraping\inventtory_data_scraping\inventtory_spiders\inventtory_spiders\spiders\ww_espacenet_WO.py", line 148, in parse_patent_link
    item['priority_numbers'] = response.xpath('//td[@class="printTableText"]//text()').re('(\w{2}\d{12}\s*\d{8})')[1]
IndexError: list index out of range
2016-11-28 13:51:44 [scrapy] ERROR: Spider error processing <GET https://worldwide.espacenet.com/data/publicationDetails/biblio?DB=EPODOC&II=23&ND=3&adjacent=true&locale=en_EP&FT=D&date=20161124&CC=WO&NR=2016187606A1&KC=A1> (referer: https://worldwide.espacenet.com/data/searchResults?page=72&locale=en_EP&DB=EPODOC&ST=advanced&TI=&AB=&PN=WO&AP=&PR=&PD=&PA=&IN=&CPC=&IC=&Submit=Search)
Traceback (most recent call last):
  File "c:\python27\lib\site-packages\scrapy\utils\defer.py", line 102, in iter_errback
    yield next(it)
  File "c:\python27\lib\site-packages\scrapy\spidermiddlewares\offsite.py", line 29, in process_spider_output
    for x in result:
  File "c:\python27\lib\site-packages\scrapy\spidermiddlewares\referer.py", line 22, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "c:\python27\lib\site-packages\scrapy\spidermiddlewares\urllength.py", line 37, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "c:\python27\lib\site-packages\scrapy\spidermiddlewares\depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "C:\Users\serap\Documents\inventtory_data_scraping\inventtory_data_scraping\inventtory_spiders\inventtory_spiders\spiders\ww_espacenet_WO.py", line 148, in parse_patent_link
    item['priority_numbers'] = response.xpath('//td[@class="printTableText"]//text()').re('(\w{2}\d{12}\s*\d{8})')[1]
IndexError: list index out of range
2016-11-28 13:51:49 [scrapy] ERROR: Spider error processing <GET https://worldwide.espacenet.com/data/publicationDetails/biblio?DB=EPODOC&II=22&ND=3&adjacent=true&locale=en_EP&FT=D&date=20161124&CC=WO&NR=2016187406A1&KC=A1> (referer: https://worldwide.espacenet.com/data/searchResults?page=72&locale=en_EP&DB=EPODOC&ST=advanced&TI=&AB=&PN=WO&AP=&PR=&PD=&PA=&IN=&CPC=&IC=&Submit=Search)
Traceback (most recent call last):
  File "c:\python27\lib\site-packages\scrapy\utils\defer.py", line 102, in iter_errback
    yield next(it)
  File "c:\python27\lib\site-packages\scrapy\spidermiddlewares\offsite.py", line 29, in process_spider_output
    for x in result:
  File "c:\python27\lib\site-packages\scrapy\spidermiddlewares\referer.py", line 22, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "c:\python27\lib\site-packages\scrapy\spidermiddlewares\urllength.py", line 37, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "c:\python27\lib\site-packages\scrapy\spidermiddlewares\depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "C:\Users\serap\Documents\inventtory_data_scraping\inventtory_data_scraping\inventtory_spiders\inventtory_spiders\spiders\ww_espacenet_WO.py", line 148, in parse_patent_link
    item['priority_numbers'] = response.xpath('//td[@class="printTableText"]//text()').re('(\w{2}\d{12}\s*\d{8})')[1]
IndexError: list index out of range
2016-11-28 13:52:02 [scrapy] ERROR: Spider error processing <GET https://worldwide.espacenet.com/data/publicationDetails/biblio?DB=EPODOC&II=20&ND=3&adjacent=true&locale=en_EP&FT=D&date=20161124&CC=WO&NR=2016186978A1&KC=A1> (referer: https://worldwide.espacenet.com/data/searchResults?page=72&locale=en_EP&DB=EPODOC&ST=advanced&TI=&AB=&PN=WO&AP=&PR=&PD=&PA=&IN=&CPC=&IC=&Submit=Search)
Traceback (most recent call last):
  File "c:\python27\lib\site-packages\scrapy\utils\defer.py", line 102, in iter_errback
    yield next(it)
  File "c:\python27\lib\site-packages\scrapy\spidermiddlewares\offsite.py", line 29, in process_spider_output
    for x in result:
  File "c:\python27\lib\site-packages\scrapy\spidermiddlewares\referer.py", line 22, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "c:\python27\lib\site-packages\scrapy\spidermiddlewares\urllength.py", line 37, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "c:\python27\lib\site-packages\scrapy\spidermiddlewares\depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "C:\Users\serap\Documents\inventtory_data_scraping\inventtory_data_scraping\inventtory_spiders\inventtory_spiders\spiders\ww_espacenet_WO.py", line 148, in parse_patent_link
    item['priority_numbers'] = response.xpath('//td[@class="printTableText"]//text()').re('(\w{2}\d{12}\s*\d{8})')[1]
IndexError: list index out of range
2016-11-28 13:52:09 [scrapy] ERROR: Spider error processing <GET https://worldwide.espacenet.com/data/publicationDetails/biblio?DB=EPODOC&II=19&ND=3&adjacent=true&locale=en_EP&FT=D&date=20161124&CC=WO&NR=2016186907A1&KC=A1> (referer: https://worldwide.espacenet.com/data/searchResults?page=72&locale=en_EP&DB=EPODOC&ST=advanced&TI=&AB=&PN=WO&AP=&PR=&PD=&PA=&IN=&CPC=&IC=&Submit=Search)
Traceback (most recent call last):
  File "c:\python27\lib\site-packages\scrapy\utils\defer.py", line 102, in iter_errback
    yield next(it)
  File "c:\python27\lib\site-packages\scrapy\spidermiddlewares\offsite.py", line 29, in process_spider_output
    for x in result:
  File "c:\python27\lib\site-packages\scrapy\spidermiddlewares\referer.py", line 22, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "c:\python27\lib\site-packages\scrapy\spidermiddlewares\urllength.py", line 37, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "c:\python27\lib\site-packages\scrapy\spidermiddlewares\depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "C:\Users\serap\Documents\inventtory_data_scraping\inventtory_data_scraping\inventtory_spiders\inventtory_spiders\spiders\ww_espacenet_WO.py", line 148, in parse_patent_link
    item['priority_numbers'] = response.xpath('//td[@class="printTableText"]//text()').re('(\w{2}\d{12}\s*\d{8})')[1]
IndexError: list index out of range
2016-11-28 13:52:16 [scrapy] ERROR: Spider error processing <GET https://worldwide.espacenet.com/data/publicationDetails/biblio?DB=EPODOC&II=18&ND=3&adjacent=true&locale=en_EP&FT=D&date=20161124&CC=WO&NR=2016186797A1&KC=A1> (referer: https://worldwide.espacenet.com/data/searchResults?page=72&locale=en_EP&DB=EPODOC&ST=advanced&TI=&AB=&PN=WO&AP=&PR=&PD=&PA=&IN=&CPC=&IC=&Submit=Search)
Traceback (most recent call last):
  File "c:\python27\lib\site-packages\scrapy\utils\defer.py", line 102, in iter_errback
    yield next(it)
  File "c:\python27\lib\site-packages\scrapy\spidermiddlewares\offsite.py", line 29, in process_spider_output
    for x in result:
  File "c:\python27\lib\site-packages\scrapy\spidermiddlewares\referer.py", line 22, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "c:\python27\lib\site-packages\scrapy\spidermiddlewares\urllength.py", line 37, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "c:\python27\lib\site-packages\scrapy\spidermiddlewares\depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "C:\Users\serap\Documents\inventtory_data_scraping\inventtory_data_scraping\inventtory_spiders\inventtory_spiders\spiders\ww_espacenet_WO.py", line 148, in parse_patent_link
    item['priority_numbers'] = response.xpath('//td[@class="printTableText"]//text()').re('(\w{2}\d{12}\s*\d{8})')[1]
IndexError: list index out of range
2016-11-28 13:52:23 [scrapy] ERROR: Spider error processing <GET https://worldwide.espacenet.com/data/publicationDetails/biblio?DB=EPODOC&II=17&ND=3&adjacent=true&locale=en_EP&FT=D&date=20161124&CC=WO&NR=2016186737A1&KC=A1> (referer: https://worldwide.espacenet.com/data/searchResults?page=72&locale=en_EP&DB=EPODOC&ST=advanced&TI=&AB=&PN=WO&AP=&PR=&PD=&PA=&IN=&CPC=&IC=&Submit=Search)
Traceback (most recent call last):
  File "c:\python27\lib\site-packages\scrapy\utils\defer.py", line 102, in iter_errback
    yield next(it)
  File "c:\python27\lib\site-packages\scrapy\spidermiddlewares\offsite.py", line 29, in process_spider_output
    for x in result:
  File "c:\python27\lib\site-packages\scrapy\spidermiddlewares\referer.py", line 22, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "c:\python27\lib\site-packages\scrapy\spidermiddlewares\urllength.py", line 37, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "c:\python27\lib\site-packages\scrapy\spidermiddlewares\depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "C:\Users\serap\Documents\inventtory_data_scraping\inventtory_data_scraping\inventtory_spiders\inventtory_spiders\spiders\ww_espacenet_WO.py", line 148, in parse_patent_link
    item['priority_numbers'] = response.xpath('//td[@class="printTableText"]//text()').re('(\w{2}\d{12}\s*\d{8})')[1]
IndexError: list index out of range
2016-11-28 13:52:30 [scrapy] ERROR: Spider error processing <GET https://worldwide.espacenet.com/data/publicationDetails/biblio?DB=EPODOC&II=16&ND=3&adjacent=true&locale=en_EP&FT=D&date=20161124&CC=WO&NR=2016186693A1&KC=A1> (referer: https://worldwide.espacenet.com/data/searchResults?page=72&locale=en_EP&DB=EPODOC&ST=advanced&TI=&AB=&PN=WO&AP=&PR=&PD=&PA=&IN=&CPC=&IC=&Submit=Search)
Traceback (most recent call last):
  File "c:\python27\lib\site-packages\scrapy\utils\defer.py", line 102, in iter_errback
    yield next(it)
  File "c:\python27\lib\site-packages\scrapy\spidermiddlewares\offsite.py", line 29, in process_spider_output
    for x in result:
  File "c:\python27\lib\site-packages\scrapy\spidermiddlewares\referer.py", line 22, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "c:\python27\lib\site-packages\scrapy\spidermiddlewares\urllength.py", line 37, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "c:\python27\lib\site-packages\scrapy\spidermiddlewares\depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "C:\Users\serap\Documents\inventtory_data_scraping\inventtory_data_scraping\inventtory_spiders\inventtory_spiders\spiders\ww_espacenet_WO.py", line 148, in parse_patent_link
    item['priority_numbers'] = response.xpath('//td[@class="printTableText"]//text()').re('(\w{2}\d{12}\s*\d{8})')[1]
IndexError: list index out of range
